### ISSUE TITLE
example_identifier for SwissProt

### ISSUE THREAD

**Issue by ariutta** [bridgedb/datasources#11]
[datasources.txt](https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources.txt#L128) lists `CALM_HUMAN` as an `example_identifier` for SwissProt. [datasources_headers.txt](https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.bio/resources/org/bridgedb/bio/datasources_headers.txt#L12) defines `example_identifier` as

> A valid example of a datasource identifier; may not be representative of all types of identifiers from a given resource    1851_s_at

I discussed this with Nick Juty, and the result was that `CALM_HUMAN` is an [entry name](http://www.uniprot.org/help/entry_name):

> The entry name is a useful mnemonic means of identifying a sequence, but, unlike the accession number, it is not a stable identifier.

Further comment from Nick:

> I think that the gene name is CALM, and in humans it is CALM_HUMAN. But we use the identifier provided by UniProt for the record, not for the gene or protein. The identifier for the record is the stable identifier.

So is datasources.txt wrong to list `CALM_HUMAN` as an example identifier for SwissProt? Should the example_identifier instead be `P62158`?

**Comment by egonw** [comment]
I guess this was fixed at some point.
