### ISSUE TITLE
Update HGNC linkouts

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/datasources#12]
See also bridgedb/datasources#6 ; HGNC linkout on WikiPathways website, and PathVisio don't work...

- [ ]  WikiPathways [WP4868](https://www.wikipathways.org/index.php/Pathway:WP4868)

![image](https://user-images.githubusercontent.com/26277832/115254951-223e2e00-a12e-11eb-9946-f61ae0411c72.png)
Result:
![image](https://user-images.githubusercontent.com/26277832/115255120-400b9300-a12e-11eb-9b0e-be02c3eb1821.png)

- [ ] PathVisio (WP4868):
![image](https://user-images.githubusercontent.com/26277832/115254672-dc816580-a12d-11eb-91fe-f1137d149bdd.png)
Result:
![image](https://user-images.githubusercontent.com/26277832/115254769-f4f18000-a12d-11eb-8f89-e9c5ec2b7975.png)

**Comment by egonw** [comment]
Yes, we have a problem here. The URL for symbols just don't work. I'll have to remove it.

**Comment by DeniseSl22** [comment]
But, that would mean that all GeneProducts+Proteins annotated with HGNC symbol, will not have a working linkout on the WP website... Should we write a bot, to convert them to HGNC IDs (existing ones and in the future)? @mkutmon @AlexanderPico ?

**Comment by tabbassidaloii** [comment]
any update on this issue?

**Comment by DeniseSl22** [comment]
Nope, we should make updates to all GPMLs with HGNC symbols in them, to get the linkouts working again. Also, what would be good to change in PV4, is not showing HGNC symbols anymore when looking for an identifier @mkutmon . And we could write a unit test for HGNC symbols in the future, so we can curate them later @egonw .

**Comment by tabbassidaloii** [comment]
We can try to fix it in the hackathon planned in Feb

**Comment by egonw** [comment]
See also: https://github.com/bridgedb/datasources/issues/6#issuecomment-1380150769

**Comment by Chris-Evelo** [comment]
I was just reading the whole threat. I think it makes perfect sense for people to use HGNC symbols and not ID's. Actually conceptually HGNC symbols were meant to be the thing use d by the community as they are both unique, can be resolved and are both human (add meaning) and machine readable. HGNC thus is a special case where we want to allow people to use both symbols and IDs. If you want to automate anything it would be more the other way around. Like have a quick (hover?) lookup where you can find what symbol is meant if only the ID is there.

**Comment by DeniseSl22** [comment]
@Chris-Evelo : that's the thing, the symbols are no longer resolvable... Through BridgeDb, we can retrieve the HGNC symbol based on any other ID, but if the HGNC symbol is the ID used for annotation, the linkouts don't work anymore.

**Comment by Chris-Evelo** [comment]
OK, I do understand now, and of course, we want them to be resolved. So is that an identifiers.org issue? n2t.net actually resolves the CURIE. I just tried n2t.net/hgnc:septin1 and that resolves fine. Of course, we could also solve it by converting any hgnc symbols to hgnc IDs on the fly, before we do the linkout. That would still be inline with the philosophy of the human gene name consortium is that human users should not have to know or ever see the identifiers.

**Comment by egonw** [comment]
Step 2 was to test if we had non-numeric `HGNC Accession numbers` which we do not seem to have. Not many anyway: https://bit.ly/3H1QUhZ

**Comment by egonw** [comment]
> We can try to fix it in the hackathon planned for Feb

@tabbassidaloii, great idea! It seems to me what we are missing in the BridgeDb mapping files are mappings between the `HGNC symbol`s and `HGNC Accession Number`s. Correct?

Now, to use any such work, we typically always need a new PathVisio release too, tho the webservices and therefore WikiPathways, but also the RDF generation can still use a recent BridgeDb directly.

**Comment by tabbassidaloii** [comment]
> > We can try to fix it in the hackathon planned for Feb
> 
> @tabbassidaloii, great idea! It seems to me what we are missing in the BridgeDb mapping files are mappings between the `HGNC symbol`s and `HGNC Accession Number`s. Correct?

I am not sure if that is correct. But I look into it.

**Comment by egonw** [comment]
Fixed. But I still like to see those mappings.
