### ISSUE TITLE
Minor: column names are not great

### ISSUE THREAD

**Issue by AlexanderPico** [bridgedb/datasources#19]
https://github.com/bridgedb/datasources/blob/main/organisms.tsv

First two columns are really correct. Better headers would be: genus, species

Can we change these or will that mess up downstream tools?

**Comment by egonw** [comment]
Not sure about the downstream consequences, but we can check for that.

**Comment by egonw** [comment]
Done in https://github.com/bridgedb/datasources/commit/f735d061928e0c3167da2a6d46eb259fc78f6cb1

Let's see what happens.
