### ISSUE TITLE
WikiPathways linkouts

### ISSUE THREAD

**Issue by fehrhart** [bridgedb/datasources#2]
Tested the gene/product linkouts on Wikipathways

- [x] Affymetrix - log in required - is that intended, shall we keep that?
- [x] Agilent, Illumina - not a link, just a number - is that intended?
- [x] Ensembl - patch bridgedb/BridgeDb#146 and bridgedb/BridgeDb#147 
- [x] UCSC genome browser - does not work - action required
- [x] UniGene - does not work - action required
- [x] WikiGenes - connection timeout - check again and then decide

**Comment by egonw** [comment]
"Agilent, Illumina - not a link, just a number - is that intended?" - There is indeed no URL pattern, so intended.

**Comment by egonw** [comment]
"Affymetrix - log in required - is that intended, shall we keep that?" - Yes, let's do that. Generally, if there is no clear reason to remove it, it's saver to keep it, because someone may actually use it (e.g. someone with a login).

**Comment by egonw** [comment]
WikiGenes fixed by https://github.com/bridgedb/datasources/commit/2530dbb0dfb52d59602ee9b99e55e18717bba4d3

**Comment by egonw** [comment]
UniGene no longer exists: https://web.archive.org/web/20210425074853/https://ncbiinsights.ncbi.nlm.nih.gov/tag/unigene/

**Comment by egonw** [comment]
@mkutmon, @Chris-Evelo, what do you know about the UCSC genome browser link? How is/was this used?

**Comment by Chris-Evelo** [comment]
Not sure this answers your question. But traditionally the UCSC genome browser is one of the 3 most used browsers for the human genome, next to ENSEMBL and NCBI. I haven't looked at it in a while, but traditionally it had some tracks for things like variants not easily available from other browsers. I suppose the three converged, but many people get used to a specific browser.

**Comment by egonw** [comment]
> Not sure this answers your question. But traditionally the UCSC genome browser is one of the 3 most used browsers for the human genome, next to ENSEMBL and NCBI. I haven't looked at it in a while, but traditionally it had some tracks for things like variants not easily available from other browsers. I suppose the three converged, but many people get used to a specific browser.

Okay, then we need to figure out what the currently working URL pattern is.

**Comment by egonw** [comment]
Remaining issue continued here: https://github.com/bridgedb/datasources/issues/17
