### ISSUE TITLE
Add Bioregistry prefix column

### ISSUE THREAD

**Issue by cthoyt** [bridgedb/datasources#22]
It's great you're curating a registry here! I saw it's linking out to miriam prefixes so I figured it would be good to include [Bioregistry](https://github.com/biopragmatics/bioregistry) ones as well. This way it would be easier to monitor any potentially novel contributions here and suck them back in to the Bioregistry

I can write a script that does this based on Miriam and Wikidata mappings to demonstrate.

Edit: while working on this, I noticed there were several invalid MIRIAM prefixes, which lead to #23

**Comment by DeniseSl22** [comment]
https://github.com/bridgedb/datasources/pull/26
