### ISSUE TITLE
update the namespace for HGNC and Ensembl

### ISSUE THREAD

**Issue by tabbassidaloii** [bridgedb/datasources#44]
e.g. `https://www.genenames.org/data/hgnc_data.php?hgnc_id=` should be replaced with `https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/`

**Comment by tabbassidaloii** [comment]
Also, adding unit tests for links out maybe for all the data sources

**Comment by egonw** [comment]
@tabbassidaloii, oh, that's really weird. This was fixed almost a year ago: https://github.com/bridgedb/datasources/commit/edad1320daf605bb80d6b3376f740fc75bd96be4

**Comment by tabbassidaloii** [comment]
Okay, this is weird.
I didn't use the most recent version of BridgeDb because of some other issue.
I should check. Will share the details.
