### ISSUE TITLE
request for adding this species: Rosmarinus officinalis

### ISSUE THREAD

**Issue by egonw** [bridgedb/datasources#50]
cc @sneumann

**Comment by egonw** [comment]
@sneumann, this one? https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=39367 

Is seems *Rosmarinus officinalis* is the old name?

**Comment by sneumann** [comment]
Hi, I can confirm we are talking about 39367 "current name: Salvia rosmarinus (L.) Schleid., 1852".
Botany and Synonyms is quite complex ... Yours, Steffen

**Comment by egonw** [comment]
Thanks!

**Comment by egonw** [comment]
Added: https://github.com/bridgedb/datasources/releases/tag/20240925
