### ISSUE TITLE
Unrecognised HGNC URI pattern

### ISSUE THREAD

**Issue by ianwdunlop** [bridgedb/datasources#6]
The pattern `http://identifiers.org/hgnc/HGNC%253A29350` was found in a linkset but was not recognized by BridgeDB. However it does redirect to the correct place which suggests that identifiers.org does recognize it. So, either the pattern needs added to BridgeDB or the linkset file changed.
The URI looks like it has been escaped wrong in some way.

**Comment by egonw** [comment]
Bioregistry/Identifiers.org (via Bioregistry):

- hgnc.symbol: https://bioregistry.io/registry/hgnc.symbol
- hgnc: https://bioregistry.io/registry/hgnc

BridgeDb only has one.

**Comment by egonw** [comment]
Closing this for now. So much has changed, and the IMS currently needs a lot of attention anyway, but still no funding for this.
