### ISSUE TITLE
Incorrect linkout patterns or example identifiers

### ISSUE THREAD

**Issue by ariutta** [bridgedb/datasources#8]
The following linkout pattern + example identifier combinations appear to be outdated or incorrect:

Do not resolve:
- [x] NuGO wiki: http://wiki.nugo.org/index.php/HMDB00001
- [x] LIPID MAPS: http://www.lipidmaps.org/data/get_lm_lipids_dbgif.php?LM_ID=LMPR0102010012
- [x] Gramene Rice and Rice Ensembl Gene: see bridgedb/datasources#3 
- [x] UCSC Genome Browser: http://genome.ucsc.edu/cgi-bin/hgTracks?position=uc001tyh.1
- [x] RFAM: http://www.sanger.ac.uk/cgi-bin/Rfam/getacc?RF00066
- [x] IPI: http://www.ebi.ac.uk/cgi-bin/dbfetch?db=IPI&id=IPI00000001&format=default
- [x] miRBase Sequence: http://microrna.sanger.ac.uk/cgi-bin/sequences/mirna_entry.pl?acc=MI0000001
- [x] MatrixDB: http://matrixdb.ibcp.fr/cgi-bin/model/report/default?name=P00747_P07355&class=Association
- [x] MINT: http://mint.bio.uniroma2.it/mint/search/inFrameInteraction.do?interactionAc=MINT-10000
- [x] Ensembl Dog: http://www.ensembl.org/Canis_familiaris/Gene/Summary?g=ENSCAFG00000025860
- [x] Small Molecule Pathway Database: http://pathman.smpdb.ca/pathways/SMP00001/pathway

Outdated:
- [x] Pfam: http://pfam.sanger.ac.uk/family/PF01234/ should be http://pfam.xfam.org/family/PF01234/
- [x] PharmGKB Pathways: http://www.pharmgkb.org/pathway/PA146123006 should be https://www.pharmgkb.org/pathway/PA146123006
- [x] PharmGKB Drug: http://www.pharmgkb.org/drug/PA448710 should be https://www.pharmgkb.org/drug/PA448710
- [x] PharmGKB Gene: http://www.pharmgkb.org/gene/PA131 should be https://www.pharmgkb.org/gene/PA131
- [x] SGD: http://www.yeastgenome.org/cgi-bin/locus.fpl?dbid=S000028457 should be http://www.yeastgenome.org/locus/S000028457/overview
- [x] EcoGene: http://ecogene.org/geneInfo.php?eg_id=EG10173 should be http://www.ecogene.org/old/geneInfo.php?eg_id=EG10173
- [x] Gramene Maize: http://www.maizesequence.org/Zea_mays/Gene/Summary?g=GRMZM2G174107 should be http://www.gramene.org/Zea_mays/Gene/Summary?g=GRMZM2G174107 or http://ensembl.gramene.org/Zea_mays/Gene/Summary?g=GRMZM2G174107
- [x] Gramene Genes: http://www.gramene.org/db/genes/search_gene?acc=GR:0060184 should be http://archive.gramene.org/db/genes/search_gene?acc=GR:0060184
- [x] TAIR Locus: http://arabidopsis.org/servlets/TairObject?type=locus&name=AT1G01030 should be https://www.arabidopsis.org/servlets/TairObject?type=locus&name=AT1G01030
- [x] Wikidata: http://www.wikidata.org/wiki/Q407962 should be https://www.wikidata.org/wiki/Q407962
- [x] Wikipedia: http://en.wikipedia.org/wiki/Acetate should be https://en.wikipedia.org/wiki/Acetate
- [x] Rat Genome Database: http://rgd.mcw.edu/tools/genes/genes_view.cgi?id=2018 should be http://rgd.mcw.edu/rgdweb/report/gene/main.html?id=2018
- [x] RefSeq: http://www.ncbi.nlm.nih.gov/entrez/viewer.fcgi?val=NP_012345 should be http://www.ncbi.nlm.nih.gov/protein/NP_012345
- [x] MaizeGDB: http://www.maizegdb.org/cgi-bin/displaylocusresults.cgi?term=acc1 should be http://maizegdb.org/gene_center/gene/acc1
- [x] BRENDA: http://www.brenda-enzymes.org/php/result_flat.php4?ecno=1.1.1.1 should be http://www.brenda-enzymes.org/enzyme.php?ecno=1.1.1.1

**Comment by egonw** [comment]
BRENDA updated: https://github.com/bridgedb/datasources/commit/64d367e8e7a04ea266f9bb29591adeb0606389cd

**Comment by egonw** [comment]
Updated RefSeq: https://github.com/bridgedb/datasources/commit/451ba059d5abc6502048310517746861615b7e29

**Comment by egonw** [comment]
- updated PharmGKB: https://github.com/bridgedb/datasources/commit/65a538c59473c7eb757978aba0bb0d2dcef39147#diff-dc744ff55cde772208a39f3c9869251f9ba631f137b9a4b8ad30c46ce314db5e
- updated MaizeGDB: https://github.com/bridgedb/datasources/commit/24c6915ab667ad9918d7239ba036d98123799263#diff-dc744ff55cde772208a39f3c9869251f9ba631f137b9a4b8ad30c46ce314db5e
- updated Pfam: https://github.com/bridgedb/datasources/commit/8825f6795ecac95b6fe18b73fc99f2686134babc#diff-dc744ff55cde772208a39f3c9869251f9ba631f137b9a4b8ad30c46ce314db5e

**Comment by egonw** [comment]
Updated a few more and for two complicated ones I filed new issues.
